name: compile-extensions
on: [push]
jobs:
  compile-python-linux-x86_64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11' 
      - name: Install Python dev dependencies
        run: |
          sudo apt update
          sudo apt install -y python3.11-dev
      - name: Install boost libraries
        run: |
          cd sp-dr-client/lib
          chmod +x install_boost.sh
          ./install_boost.sh
          make python
          cd ../python
          chmod +x bootstrap.sh
          ./bootstrap.sh test
  compile-java-linux-x86_64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # Install Java and Maven
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'oracle'
      - uses: stCarolas/setup-maven@v4.5
      # Compile the extension
      - name: Compile the extension
        run: |
          cd sp-dr-client/java
          mvn clean install
      - uses: actions/upload-artifact@v3
        with:
          name: sp-dr.jar
          path: /home/siddhartha/Documents/sp-dr/sp-dr-client/java/target/spdr_client-1.0-SNAPSHOT-jar-with-dependencies.jar
