name: compile-extensions
on: [push]
jobs:
  compile-puredata-linux-x86_64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Install cmake
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake
      - name: Install puredata
        run: |
          sudo apt-get update
          sudo apt-get install -y puredata-dev
      - name: Build and install flext
        continue-on-error: true
        run: |
          cd creative-extensions/puredata/flext
          ./bootstrap.sh
          ./configure --enable-system=pd --with-sdkdir=/usr/include/pd
          make -j$(nproc)
          sudo make install
      - name: Build puredata externals
        run: |
          cd creative-extensions/puredata
          mkdir build
          cd build
          cmake ..
          make
      - uses: actions/upload-artifact@v3
        with:
          name: ergojunior.pd_linux
          path: ~/Documents/Pd/externals/ergojunior/ergojunior.pd_linux
  compile-processing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # Install Java and Maven
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'oracle'
      - uses: stCarolas/setup-maven@v4.5
      # Compile the extension
      - name: Compile the extension
        run: |
          cd creative-extensions/processing
          make
      - uses: actions/upload-artifact@v3
        with:
          name: ergojunior.jar
          path: creative-extensions/processing/target/ergo_junior_controller-1.0-SNAPSHOT.jar
